#!/bin/bash

function shutdown()
{
    echo "`date +"%d.%m.%Y %T.%3N"` - Shutting down mysql"
    mysqladmin shutdown -u root
}

echo "`date +"%d.%m.%Y %T.%3N"` - Starting mysql"

/usr/sbin/mysqld --user=mysql --basedir=/usr --datadir=/var/lib/mysql --daemonize

# Allow any signal which would kill a process to stop server
trap shutdown HUP INT QUIT ABRT KILL ALRM TERM TSTP

while pgrep -u mysql mysql > /dev/null; do sleep 5; done
